import { Service, Category, EventType, City, ChecklistItem } from "./types"

export const cities: City[] = [
  { id: "kinshasa", name: "Kinshasa", province: "Kinshasa" },
  { id: "lubumbashi", name: "Lubumbashi", province: "Haut-Katanga" },
  { id: "goma", name: "Goma", province: "Nord-Kivu" },
  { id: "bukavu", name: "Bukavu", province: "Sud-Kivu" },
  { id: "kisangani", name: "Kisangani", province: "Tshopo" },
  { id: "matadi", name: "Matadi", province: "Kongo-Central" },
  { id: "mbuji-mayi", name: "Mbuji-Mayi", province: "Kasaï-Oriental" },
  { id: "kananga", name: "Kananga", province: "Kasaï-Central" },
]

export const eventTypes: EventType[] = [
  { id: "mariage", label: "Mariage", icon: "💍", desc: "Cérémonie civile, religieuse & réception" },
  { id: "dotation", label: "Dotation", icon: "🤝", desc: "Dot, pré-dot & accord des familles" },
  { id: "anniversaire", label: "Anniversaire", icon: "🎂", desc: "Enfants, adultes, surprises" },
  { id: "bapteme", label: "Baptême & Doto", icon: "👶", desc: "Baptême, doto & présentation" },
  { id: "funerailles", label: "Funérailles", icon: "🕊️", desc: "Veillées, corps présent & convoi" },
  { id: "entreprise", label: "Entreprise", icon: "💼", desc: "Séminaires, lancements & soirées" },
]

export const categories: Category[] = [
  { id: "all", name: "Tous", icon: "✨", count: 20 },
  { id: "salles", name: "Salles & Espaces", icon: "🏛️", count: 3 },
  { id: "traiteur", name: "Traiteur & Boissons", icon: "🍲", count: 2 },
  { id: "decoration", name: "Décoration & Fleurs", icon: "🎀", count: 2 },
  { id: "sono", name: "Sono, DJ & Lumières", icon: "🔊", count: 2 },
  { id: "photo", name: "Photo & Vidéo", icon: "📸", count: 2 },
  { id: "beaute", name: "Beauté & Mode", icon: "💄", count: 3 },
  { id: "transport", name: "Transport & Cortège", icon: "🚗", count: 2 },
  { id: "animation", name: "Animation & Musique", icon: "🎤", count: 3 },
  { id: "gateau", name: "Gâteaux & Douceurs", icon: "🎂", count: 1 },
]

export function categoryName(id: string) {
  return categories.find((c) => c.id === id)?.name ?? id
}

export function eventTypeOf(id: string) {
  return eventTypes.find((e) => e.id === id)
}

/** Checklist recommandée par type de cérémonie */
export const eventChecklists: Record<string, ChecklistItem[]> = {
  mariage: [
    { category: "salles", label: "Salle ou espace de réception" },
    { category: "traiteur", label: "Repas & boissons des invités" },
    { category: "decoration", label: "Décoration de la salle & des chaises" },
    { category: "sono", label: "Sono, DJ & éclairage" },
    { category: "photo", label: "Photographe & vidéaste" },
    { category: "beaute", label: "Coiffure, maquillage & tenues" },
    { category: "transport", label: "Voiture des mariés & cortège" },
    { category: "animation", label: "Orchestre, chorale ou MC" },
    { category: "gateau", label: "Le wedding cake" },
  ],
  dotation: [
    { category: "salles", label: "Terrain ou salle de la dot" },
    { category: "traiteur", label: "Repas des deux familles" },
    { category: "decoration", label: "Décoration & paquets cadeaux" },
    { category: "beaute", label: "Tenues traditionnelles & beauté" },
    { category: "photo", label: "Photographe pour la cérémonie" },
    { category: "sono", label: "Sono pour l'ambiance" },
    { category: "transport", label: "Transport des familles" },
  ],
  anniversaire: [
    { category: "gateau", label: "Le gâteau d'anniversaire" },
    { category: "decoration", label: "Balloons & décoration" },
    { category: "animation", label: "Animation enfants ou DJ" },
    { category: "traiteur", label: "Buffet & boissons" },
    { category: "salles", label: "Salle ou espace extérieur" },
    { category: "photo", label: "Photographe" },
  ],
  bapteme: [
    { category: "salles", label: "Salle de réception" },
    { category: "traiteur", label: "Repas de la famille" },
    { category: "decoration", label: "Décoration & fleurs" },
    { category: "photo", label: "Photographe / vidéaste" },
    { category: "gateau", label: "Gâteau de baptême" },
    { category: "animation", label: "Chorale ou animation" },
  ],
  funerailles: [
    { category: "salles", label: "Salle de deuil / parcelle" },
    { category: "sono", label: "Sonorisation de la veillée" },
    { category: "traiteur", label: "Repas des personnes en deuil" },
    { category: "transport", label: "Convoi funèbre & transport" },
    { category: "photo", label: "Couverture photo / vidéo" },
    { category: "animation", label: "Chorale & louange" },
  ],
  entreprise: [
    { category: "salles", label: "Salle de conférence / espace" },
    { category: "traiteur", label: "Cocktail & catering" },
    { category: "sono", label: "Sono & écran de projection" },
    { category: "photo", label: "Photographe officiel" },
    { category: "decoration", label: "Signalétique & décoration" },
    { category: "animation", label: "MC & animation" },
  ],
}

export function checklistFor(eventType: string): ChecklistItem[] {
  return eventChecklists[eventType] ?? eventChecklists.mariage
}

export const services: Service[] = [
  // ─── SALLES & ESPACES ───────────────────────────────────────────
  {
    id: "salle-kin",
    name: "Grand Salon Kin — Salle de réception",
    category: "salles",
    description: "Salle climatisée de 300 places, avenue du 24 novembre",
    longDescription:
      "La salle la plus demandée de Gombe pour les mariages et dotations. 300 places assises, climatisation centrale, scène pour orchestre, parking gardé 24h pour 60 véhicules, groupe électrogène de pleine puissance. Le personnel d'accueil (2 hôtesses + sécurité) est inclus. Décoration possible via nos partenaires.",
    price: 600,
    priceUnit: "la journée",
    duration: 600,
    rating: 4.9,
    reviews: 148,
    image: "/images/hall-1.jpg",
    images: ["/images/hall-1.jpg", "/images/deco-1.jpg"],
    provider: {
      name: "Grand Salon Kin",
      avatar: "/images/avatar-1.jpg",
      verified: true,
      experience: "15 ans d'expérience",
      rating: 4.9,
    },
    city: "Kinshasa",
    location: "Gombe · Av. du 24 novembre",
    features: [
      "300 places assises",
      "Climatisation centrale",
      "Scène + loge mariés",
      "Parking gardé 60 voitures",
      "Groupe électrogène",
      "Hôtesses d'accueil incluses",
    ],
    popular: true,
    instant: true,
  },
  {
    id: "salle-palmier",
    name: "Le Palmier Palace — Espace événementiel",
    category: "salles",
    description: "Espace de 250 places avec cour extérieure ombragée",
    longDescription:
      "Espace polyvalent au cœur de Lubumbashi : grande salle de 250 places + cour extérieure ombragée pour les cocktail et photographies. Cuisine sur place disponible pour vos traiteurs, chapiteaux de réserve en cas de pluie, et sonorisation de base incluse. Idéal mariages, dotations et séminaires.",
    price: 450,
    priceUnit: "la journée",
    duration: 600,
    rating: 4.8,
    reviews: 96,
    image: "/images/hall-2.jpg",
    images: ["/images/hall-2.jpg"],
    provider: {
      name: "Palmier Palace",
      avatar: "/images/avatar-2.jpg",
      verified: true,
      experience: "Espace premium",
      rating: 4.8,
    },
    city: "Lubumbashi",
    location: "Golf · Av. Kasaï",
    features: ["250 places", "Cour extérieure", "Cuisine sur place", "Chapiteaux anti-pluie", "Sono de base"],
    instant: true,
  },
  {
    id: "salle-jardin",
    name: "Jardin du Fleuve — Réception en plein air",
    category: "salles",
    description: "Jardin au bord du fleuve, guirlandes lumineuses au couchant",
    longDescription:
      "Un jardin magique au bord de l'eau pour vos réceptions au coucher du soleil : pelouse de 800 m², guirlandes lumineuses, kiosque pour les photos de couple, et vue imprenable sur le fleuve. Capacité 150 invités. Parfait pour les mariages intimistes, dotations et anniversaires.",
    price: 350,
    priceUnit: "la soirée",
    duration: 360,
    rating: 4.9,
    reviews: 74,
    image: "/images/garden-1.jpg",
    images: ["/images/garden-1.jpg", "/images/deco-2.jpg"],
    provider: {
      name: "Jardin du Fleuve",
      avatar: "/images/avatar-3.jpg",
      verified: true,
      experience: "Le spot des couchers de soleil",
      rating: 4.9,
    },
    city: "Kinshasa",
    location: "Ma Vallée · Ngaliema",
    features: ["150 invités", "Guirlandes lumineuses", "Kiosque photos", "Vue fleuve", "Parking sécurisé"],
    popular: true,
  },

  // ─── TRAITEUR ───────────────────────────────────────────────────
  {
    id: "traiteur-maman-ngo",
    name: "Chez Maman Ngo — Traiteur cérémonie",
    category: "traiteur",
    description: "Pondu, makemba, poisson grillé, riz gras — buffet généreux",
    longDescription:
      "La référence du traiteur traditionnel congolais pour les grandes occasions. Buffet complet : pondu, chikwanga, makemba, riz gras, poulet mayonnaise, poisson grillé, goat meat en sauce. Service en buffet avec vaisselle complète, serveurs en tenue, et boissons locales incluses (Primus, Fanta, eau). Goûter avant de commander, c'est possible !",
    price: 12,
    priceUnit: "par invité",
    duration: 300,
    rating: 4.9,
    reviews: 213,
    image: "/images/food-1.jpg",
    images: ["/images/food-1.jpg", "/images/food-2.jpg"],
    provider: {
      name: "Maman Ngo & Filles",
      avatar: "/images/avatar-6.jpg",
      verified: true,
      experience: "20 ans de fourneaux",
      rating: 4.9,
    },
    city: "Kinshasa",
    location: "Bandal · Cuisines centrales",
    features: [
      "Buffet complet congolais",
      "Serveurs en tenue inclus",
      "Vaisselle & nappes fournies",
      "Boissons locales incluses",
      "Dégustation préalable",
      "Tentes & matériel sur option",
    ],
    popular: true,
    instant: true,
  },
  {
    id: "traiteur-saveurs",
    name: "Saveurs du Congo — Catering moderne",
    category: "traiteur",
    description: "Cuisine congolaise revisitée + menu continental",
    longDescription:
      "Catering haut de gamme qui marie saveurs congolaises et présentation moderne : minibuffets dressés, stations de brochettes de tilapia, captain's dinner pour la table d'honneur. Options végétariennes et menus enfants. Personnel formé en hôtellerie, service à l'assiette ou au buffet au choix.",
    price: 18,
    priceUnit: "par invité",
    duration: 300,
    rating: 4.8,
    reviews: 87,
    image: "/images/food-2.jpg",
    images: ["/images/food-2.jpg"],
    provider: {
      name: "Saveurs du Congo",
      avatar: "/images/avatar-1.jpg",
      verified: true,
      experience: "Chefs formés en hôtellerie",
      rating: 4.8,
    },
    city: "Goma",
    location: "Himbi · Av. du Tourisme",
    features: ["Menu congolais + continental", "Service à l'assiette", "Table d'honneur captain", "Menus enfants", "Options végé"],
    instant: true,
  },

  // ─── DÉCORATION ────────────────────────────────────────────────
  {
    id: "deco-elegance",
    name: "Déco Élégance — Habillage salle & chaises",
    category: "decoration",
    description: "Drapés, housses, table d'honneur et arche de fleurs",
    longDescription:
      "Transformez n'importe quelle salle en écrin : habillage complet des chaises, drapés plafond, table d'honneur composée, arche de fleurs pour l'entrée des mariés et chemin de table fleuri. Équipe de 6 décoratrices, montage la veille, démontage inclus. Rendez-vous de conception offert.",
    price: 450,
    priceUnit: "la prestation",
    duration: 480,
    rating: 4.9,
    reviews: 132,
    image: "/images/deco-1.jpg",
    images: ["/images/deco-1.jpg", "/images/hall-2.jpg"],
    provider: {
      name: "Déco Élégance",
      avatar: "/images/avatar-4.jpg",
      verified: true,
      experience: "300+ cérémonies décorées",
      rating: 4.9,
    },
    city: "Kinshasa",
    location: "Limete · Atelier central",
    features: ["Habillage chaises", "Drapés plafond", "Table d'honneur", "Arche de fleurs", "Montage la veille", "Maquette 3D avant"],
    popular: true,
  },
  {
    id: "deco-fleurs",
    name: "Fleurs & Lumières — Déco extérieure",
    category: "decoration",
    description: "Guirlandes, luminaires et compositions florales géantes",
    longDescription:
      "Spécialistes des cérémonies en plein air : guirlandes Edison suspendues, lampes à panneaux solaires (indispensables avec les coupures !), compositions florales tropicales et photowall fleuri pour vos invités. Fonctionne aussi en salle. Bouquet de la mariée offert.",
    price: 350,
    priceUnit: "la prestation",
    duration: 360,
    rating: 4.8,
    reviews: 64,
    image: "/images/deco-2.jpg",
    images: ["/images/deco-2.jpg", "/images/garden-1.jpg"],
    provider: {
      name: "Fleurs & Lumières",
      avatar: "/images/avatar-5.jpg",
      verified: true,
      experience: "Déco solaire anti-coupure",
      rating: 4.8,
    },
    city: "Goma",
    location: "Les Volcans",
    features: ["Guirlandes Edison", "Éclairage solaire", "Photowall fleuri", "Bouquet mariée offert", "Compositions tropicales"],
  },

  // ─── SONO / DJ ─────────────────────────────────────────────────
  {
    id: "sono-prestige",
    name: "Prestige Sono — Son, lumières & DJ",
    category: "sono",
    description: "Pack complet 4000W, écran LED, DJ professionnel",
    longDescription:
      "Le pack son & lumière le plus complet de Kin : enceintes 4000W, table de mixage, 2 micros HF (pour le maire et les discours), éclairage LED paré, machine à fumée et écran LED 55 pouces pour vos projections. DJ professionnel qui mixe rumba, ndombolo, coupé-décalé et hits internationaux selon vos playlists. Groupe électrogène de secours inclus.",
    price: 280,
    priceUnit: "l'événement",
    duration: 360,
    rating: 4.9,
    reviews: 176,
    image: "/images/sono-1.jpg",
    images: ["/images/sono-1.jpg", "/images/sono-2.jpg"],
    provider: {
      name: "Prestige Sono",
      avatar: "/images/avatar-2.jpg",
      verified: true,
      experience: "800+ événements",
      rating: 4.9,
    },
    city: "Kinshasa",
    location: "Kintambo · Magasin central",
    features: ["4000W + 2 micros HF", "Écran LED 55\"", "Éclairage + fumée", "DJ pro 4 langues", "Groupe électrogène secours", "Montage 2h avant"],
    popular: true,
    instant: true,
  },
  {
    id: "sono-dj-jojo",
    name: "DJ Jojo Mix — Ambiance & animation musicale",
    category: "sono",
    description: "DJ + sono 2000W, karaoké et jeux d'animation",
    longDescription:
      "DJ Jojo anime vos cérémonies avec énergie : sono 2000W adaptée aux salles de 100-200 invités, éclairage ambiant, micro pour les discours, et animation de jeux (lancer de bouquet, concours de danse, karaoké). Spécialiste des anniversaires et dotations. Playlist validée avec vous 48h avant.",
    price: 180,
    priceUnit: "l'événement",
    duration: 360,
    rating: 4.8,
    reviews: 118,
    image: "/images/sono-2.jpg",
    images: ["/images/sono-2.jpg"],
    provider: {
      name: "DJ Jojo Mix",
      avatar: "/images/avatar-3.jpg",
      verified: true,
      experience: "Résident 5 ans",
      rating: 4.8,
    },
    city: "Lubumbashi",
    location: "Kenya · Quartier golf",
    features: ["Sono 2000W", "Micro discours", "Jeux d'animation", "Playlist sur mesure", "Éclairage ambiant"],
    instant: true,
  },

  // ─── PHOTO / VIDÉO ─────────────────────────────────────────────
  {
    id: "photo-memoire",
    name: "Studio Mémoire — Photo & film du jour J",
    category: "photo",
    description: "2 photographes + 1 vidéaste, film livré en 7 jours",
    longDescription:
      "Une équipe complète pour ne rien manquer : 2 photographes (cérémonie religieuse + réception), 1 vidéaste avec drone, album photo premium 40 pages et film récap de 5 à 10 minutes livré en 7 jours sur clé USB + lien WhatsApp partageable. Séance engagement (pré-mariage) offerte.",
    price: 300,
    priceUnit: "la journée",
    duration: 600,
    rating: 4.9,
    reviews: 154,
    image: "/images/photo-1.jpg",
    images: ["/images/photo-1.jpg", "/images/photo-2.jpg"],
    provider: {
      name: "Studio Mémoire",
      avatar: "/images/avatar-5.jpg",
      verified: true,
      experience: "400+ mariages filmés",
      rating: 4.9,
    },
    city: "Kinshasa",
    location: "Kasa-Vubu · Studio principal",
    features: ["2 photographes + vidéaste", "Vues drone", "Album premium 40 pages", "Film 5-10 min en 7j", "Séance engagement offerte", "Livraison USB + WhatsApp"],
    popular: true,
  },
  {
    id: "photo-nova",
    name: "Cinéma Nova — Production vidéo cérémonie",
    category: "photo",
    description: "Film 4K, clip d'invitation et aftermovie",
    longDescription:
      "Pour les cérémonies dont on parle encore 10 ans après : tournage 4K cinéma, clip d'invitation à diffuser avant le jour J, aftermovie dynamique de 3 minutes, couverture des coulisses (préparatifs, larmes des parents, entrée des mariés). Montage pro colorimétrie cinéma.",
    price: 500,
    priceUnit: "la journée",
    duration: 600,
    rating: 4.9,
    reviews: 58,
    image: "/images/photo-2.jpg",
    images: ["/images/photo-2.jpg"],
    provider: {
      name: "Cinéma Nova",
      avatar: "/images/avatar-2.jpg",
      verified: true,
      experience: "Production 4K",
      rating: 4.9,
    },
    city: "Kinshasa",
    location: "Ngaliema · Plateau",
    features: ["Tournage 4K", "Clip d'invitation", "Aftermovie 3 min", "Coulisses incluses", "Colorimétrie cinéma"],
  },

  // ─── BEAUTÉ & MODE ─────────────────────────────────────────────
  {
    id: "beaute-salon-k",
    name: "Salon Beauté K — Mariée & cortège",
    category: "beaute",
    description: "Coiffure, maquillage et ongles le jour J, à domicile",
    longDescription:
      "Le jour J, votre équipe beauté se déplace chez vous dès 5h du matin : coiffure de la mariée ( attaches, tresses, lissage au choix), maquillage longue tenue waterproof (adapté à la chaleur de Kin !), mise en beauté de 4 demoiselles d'honneur et pose d'ongles. Retouches pendant la réception incluses.",
    price: 150,
    priceUnit: "la mariée + cortège",
    duration: 300,
    rating: 4.9,
    reviews: 187,
    image: "/images/beauty-1.jpg",
    images: ["/images/beauty-1.jpg", "/images/beauty-2.jpg"],
    provider: {
      name: "Salon Beauté K",
      avatar: "/images/avatar-4.jpg",
      verified: true,
      experience: "8 ans · spécial mariage",
      rating: 4.9,
    },
    city: "Kinshasa",
    location: "Gombe · Déplacement inclus",
    features: [
      "Déplacement à domicile 5h",
      "Maquillage waterproof longue tenue",
      "4 demoiselles d'honneur incluses",
      "Tresses / attaches au choix",
      "Retouches pendant la fête",
      "Essai coiffure 1 semaine avant",
    ],
    popular: true,
    instant: true,
  },
  {
    id: "beaute-institut",
    name: "Institut Éclat — Soin & mise en beauté",
    category: "beaute",
    description: "Soin du visage, pédicure et maquillage en institut",
    longDescription:
      "Préparez votre peau 15 jours avant avec un protocole éclat : soin du visage profond, gommage corps, pédicure-luxury et le maquillage du jour J en institut (climatisé, calme, thé offert). Idéal marraines et mamans qui veulent être resplendissantes.",
    price: 60,
    priceUnit: "la prestation",
    duration: 180,
    rating: 4.8,
    reviews: 92,
    image: "/images/beauty-2.jpg",
    images: ["/images/beauty-2.jpg"],
    provider: {
      name: "Institut Éclat",
      avatar: "/images/avatar-1.jpg",
      verified: true,
      experience: "Esthéticiennes diplômées",
      rating: 4.8,
    },
    city: "Lubumbashi",
    location: "Campus · Av. Kwilu",
    features: ["Protocole éclat 15 jours", "Soin visage + gommage", "Pédicure luxury", "Maquillage jour J", "Thé & détente"],
    instant: true,
  },
  {
    id: "mode-maison-wax",
    name: "Maison Wax — Tenues de cérémonie sur mesure",
    category: "beaute",
    description: "Tenues couple + cortège en pagne, confection 10 jours",
    longDescription:
      "Sortez du commun : ensemble couple assorti en wax premium (london fabric), confection sur mesure en 10 jours avec 2 séances de mesure à domicile. Options cortège jusqu'à 8 personnes, doublure et accessoires (foulards, chapeaux, sacs). Retouches gratuites jusqu'au jour J.",
    price: 220,
    priceUnit: "le couple",
    duration: 120,
    rating: 4.9,
    reviews: 76,
    image: "/images/mode-1.jpg",
    images: ["/images/mode-1.jpg", "/images/mode-2.jpg"],
    provider: {
      name: "Maison Wax",
      avatar: "/images/avatar-3.jpg",
      verified: true,
      experience: "Atelier 12 couturiers",
      rating: 4.9,
    },
    city: "Kinshasa",
    location: "Matonge · Galerie Wakamera",
    features: ["Wax premium london", "Mesures à domicile", "Cortège jusqu'à 8 pers.", "Accessoires assortis", "Retouches gratuites", "Livraison 10 jours"],
    popular: true,
  },

  // ─── TRANSPORT ─────────────────────────────────────────────────
  {
    id: "transport-prestige",
    name: "Cortège Prestige — Voiture des mariés décorée",
    category: "transport",
    description: "Berline de luxe fleurie + chauffeur en gants blancs",
    longDescription:
      "Arrivez comme des stars : berline de luxe décorée avec fleurs fraîches et rubans satin, chauffeur en costume et gants blancs, parcours personnalisé (mairie → église → réception). Décoration de 2 voitures d'accompagnement incluse. Boissons fraîches et champagne de bienvenue à bord.",
    price: 150,
    priceUnit: "la journée",
    duration: 480,
    rating: 4.8,
    reviews: 103,
    image: "/images/car-1.jpg",
    images: ["/images/car-1.jpg", "/images/car-2.jpg"],
    provider: {
      name: "Cortège Prestige",
      avatar: "/images/avatar-6.jpg",
      verified: true,
      experience: "Flotte de 12 véhicules",
      rating: 4.8,
    },
    city: "Kinshasa",
    location: "Kintambo · Base flotte",
    features: ["Fleurs fraîches + rubans", "Chauffeur gants blancs", "2 voitures d'accompagnement", "Parcours personnalisé", "Champagne à bord", "Carburant inclus"],
    instant: true,
  },
  {
    id: "transport-convoy",
    name: "Convoy Express — Bus invités & famille",
    category: "transport",
    description: "Bus 70 places + minibus VIP, navettes assurées",
    longDescription:
      "Ne laissez aucun invité au bord de la route : bus de 70 places pour la famille, minibus VIP 15 places climatisé pour les parents des mariés, navettes gérées par un coordinateur (point de ramassage unique ou double). Chauffeurs expérimentés du trafic kinois, plan de passage préparé avec vous.",
    price: 200,
    priceUnit: "la journée",
    duration: 600,
    rating: 4.7,
    reviews: 47,
    image: "/images/car-2.jpg",
    images: ["/images/car-2.jpg"],
    provider: {
      name: "Convoy Express",
      avatar: "/images/avatar-2.jpg",
      verified: true,
      experience: "Transport événementiel",
      rating: 4.7,
    },
    city: "Kinshasa",
    location: "Ndjili · Dépôt",
    features: ["Bus 70 places", "Minibus VIP climatisé", "Coordinateur navettes", "Plan de passage", "Carburant inclus"],
  },

  // ─── ANIMATION ─────────────────────────────────────────────────
  {
    id: "animation-orchestre",
    name: "Orchestre Kin Vibes — Rumba & ndombolo live",
    category: "animation",
    description: "8 musiciens live, 3 sets de 45 min, animations danse",
    longDescription:
      "L'orchestre qui met feu à toutes les cérémonies : 8 musiciens (chants, guitares mi-solo, briquette, cuivres, percussions), 3 sets live de 45 minutes, rumba pour les parents et ndombolo enflammé pour finir. Animation de l'entrée des mariés, sebene face-à-face et dédicaces chantées avec vos noms.",
    price: 500,
    priceUnit: "la prestation",
    duration: 300,
    rating: 4.9,
    reviews: 89,
    image: "/images/band-1.jpg",
    images: ["/images/band-1.jpg"],
    provider: {
      name: "Kin Vibes",
      avatar: "/images/avatar-3.jpg",
      verified: true,
      experience: "Orchestre pro depuis 2015",
      rating: 4.9,
    },
    city: "Kinshasa",
    location: "Matonge · Local répétitions",
    features: ["8 musiciens live", "3 sets de 45 min", "Dédicaces chantées", "Entrée des mariés animée", "Sono pro incluse", "Répétition demandes spéciales"],
    popular: true,
  },
  {
    id: "animation-chorale",
    name: "Chorale Étoile du Soir — Gospel & louange",
    category: "animation",
    description: "Chorale 15 voix pour cérémonie religieuse & réception",
    longDescription:
      "Une chorale de 15 voix pour sublimer vos cérémonies religieuses : louange d'entrée, chants spéciaux pendant l'alliance, et reprise gospel festive à la réception. Répertoire sur mesure (vos chants préférés), micros et directeur de chœur inclus. Répète avec vous une fois avant le jour J.",
    price: 200,
    priceUnit: "la prestation",
    duration: 240,
    rating: 5.0,
    reviews: 71,
    image: "/images/choir-1.jpg",
    images: ["/images/choir-1.jpg", "/images/trad-1.jpg"],
    provider: {
      name: "Étoile du Soir",
      avatar: "/images/avatar-2.jpg",
      verified: true,
      experience: "15 voix · 200 cérémonies",
      rating: 5.0,
    },
    city: "Bukavu",
    location: "Ibanda · Cathédrale",
    features: ["15 choristes", "Répertoire sur mesure", "Chants spéciaux alliance", "Micros inclus", "Répétition incluse"],
  },
  {
    id: "animation-enfants",
    name: "Rire & Ballons — Animation enfants",
    category: "animation",
    description: "Château gonflable, jeux, maquillage et goûter",
    longDescription:
      "Vos petits invités ne s'ennuieront plus : château gonflable, animateurs diplômés (2), atelier maquillage bébé, jeux de vitesse, danse des gagnants et mini-goûter (jus + biscuits). Idéal anniversaires, doto et baptêmes. Sécurité : zone clôturée + animateur dédié par tranche de 10 enfants.",
    price: 120,
    priceUnit: "l'après-midi",
    duration: 240,
    rating: 4.9,
    reviews: 134,
    image: "/images/kids-1.jpg",
    images: ["/images/kids-1.jpg", "/images/kids-2.jpg"],
    provider: {
      name: "Rire & Ballons",
      avatar: "/images/avatar-4.jpg",
      verified: true,
      experience: "Spécialistes 3-12 ans",
      rating: 4.9,
    },
    city: "Goma",
    location: "Katindo · Déplacement 15 km",
    features: ["Château gonflable", "2 animateurs diplômés", "Maquillage enfants", "Mini-goûter inclus", "1 animateur / 10 enfants"],
    instant: true,
  },

  // ─── GÂTEAU ────────────────────────────────────────────────────
  {
    id: "gateau-douceurs",
    name: "Douceurs de Kin — Wedding cake sur mesure",
    category: "gateau",
    description: "3 étages, design personnalisé, livraison le jour J",
    longDescription:
      "Le gâteau qui fait tourner les têtes : 3 étages personnalisés (couleurs de votre déco, prénoms des mariés, fleurs sucrées), génoise moelleuse garniture au choix (chocolat, vanille-frangipane, ananas-coco). Servi avec coupe cérémoniale et couteau doré. Livraison et montage sur place le jour J.",
    price: 120,
    priceUnit: "le gâteau 3 étages",
    duration: 60,
    rating: 4.9,
    reviews: 158,
    image: "/images/kids-2.jpg",
    images: ["/images/kids-2.jpg", "/images/kids-1.jpg"],
    provider: {
      name: "Douceurs de Kin",
      avatar: "/images/avatar-1.jpg",
      verified: true,
      experience: "Pâtisserie fine depuis 2018",
      rating: 4.9,
    },
    city: "Kinshasa",
    location: "Lemba · Avenue de la Libération",
    features: ["3 étages personnalisés", "Fleurs sucrées", "Coupe cérémoniale incluse", "Livraison & montage", "Dégustation offerte", "Mini-gâteaux invités en option"],
    popular: true,
    instant: true,
  },
]

export const paymentMethods = [
  { id: "mpesa", name: "M-Pesa", desc: "Vodacom", color: "bg-red-600", hint: "+243 8x xxx xxx" },
  { id: "orange", name: "Orange Money", desc: "Orange RDC", color: "bg-orange-500", hint: "+243 7x xxx xxx" },
  { id: "airtel", name: "Airtel Money", desc: "Airtel Congo", color: "bg-red-700", hint: "+243 9x xxx xxx" },
]
